

import { Router, Response, Request} from "express";
import { requireAuth } from "../middleware/auth";
import sql from "../db"

const relationshipRouter = Router();


// route to generate new relationship code + need to use POST since we want timestamp 
// code will be generated by database 
relationshipRouter.post("/", requireAuth, async (req: Request, res: Response) => {

    try {
        const userId = (req as any).user.id;
        
        // check if it exists first

        const [existing] = await sql`
        SELECT id FROM relationship
        WHERE user1_id = ${userId} OR user2_id = ${userId}
        `;

        if (existing) {
            res.status(400).json({ error: "You are already in a relationship"});
            return;
        }
        // code will be autogenerated by the database 
        const [relationship] = await sql `
        INSERT INTO relationship (user1_id)
        VALUES (${userId})
        RETURNING code, user1_id, user2_id, streak_counter, created_at  
        `;

        res.status(201).json({ relationship });

    } catch (error) {

        res.status(500).json({ error: "Internal server error" });
    }
});


// route to add a new user to a new relationship code, done by PATCH

relationshipRouter.patch("/add", requireAuth, async(req: Request, res: Response) => {

    try {
        const userId = (req as any).user.id;
        const { relationshipCode } = req.body;

        if (!relationshipCode) {
            return res.status(400).json({ error: "user did not request to any relationship" })
        }

        const [existing] = await sql`
            SELECT user1_id FROM relationship
            WHERE code = ${relationshipCode}
        `;

        if (!existing) {
            res.status(404).json({ error: "Relationship code not found" });
            return;
        }

        if (existing.user1_id === userId) {
            return res.status(400).json({ error: "you cannot join your own relationship" })
        }

        const[relationship] = await sql `
        UPDATE relationship
        SET user2_id = ${userId}
        WHERE code = ${relationshipCode} AND user2_id IS NULL
        RETURNING code, user1_id, user2_id, streak_counter
        `
        // only return the things where frontend needed it 

        res.status(200).json({relationship})

    } catch(error) {
        res.status(500).json({error:"internal server error"})
    }
});


// VERY COMPLICATED ROUTE 

// route to get code of relationship after finish generating -> take from user_id1
// route to get the streak too of relationship ( its the same route )
// route to grab timezone from both of the partners too for the front page




relationshipRouter.get("/information",requireAuth, async(req: Request, res: Response) => {
    try {


        const userId = (req as any).user.id;

        // name of partner and timezone of partner is changed temporarily 

        const [relationship] = await sql `
        SELECT r.code, r.streak_counter, r.created_at, 
        partner.preferred_name AS partner_name,partner.timezone AS partner_timezone
        FROM relationship r
        LEFT JOIN users partner ON ( CASE 
        WHEN r.user1_id = ${userId} THEN r.user2_id
        WHEN r.user2_id = ${userId} THEN r.user1_id
        END = partner.id
        )
        WHERE r.user1_id = ${userId} OR r.user2_id = ${userId}
        `
        if (!relationship) {
            res.status(404).json({ error: "relationship does not exist, create one first" });
            return;
        }

        // CASE -> tells you the partner id, user1 partner id is user2, user2 partner id is user1
        // ON -> attach their user table data together by these ids 
        // END -> return their partner id 

        res.status(200).json({ relationship });

    } catch(error) {
        res.status(500).json({error: "internal server error"})

    }

});



export default relationshipRouter;
